{{- if and .Values.interrogation.enabled (include "odigos.secretExists" .) }}
apiVersion: v1
kind: Service
metadata:
  name: odigos-interrogation-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: odigos-interrogation-redis
    odigos.io/system-object: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: odigos-interrogation-redis
  ports:
    - name: {{ .Values.interrogation.redis.portName }}
      port: {{ .Values.interrogation.redis.port }}
      targetPort: {{ .Values.interrogation.redis.port }}
{{- end }}
