{{- if and .Values.interrogation.enabled (include "odigos.secretExists" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: odigos-interrogation
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
subjects:
  - kind: ServiceAccount
    name: odigos-interrogation
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: odigos-interrogation
  apiGroup: rbac.authorization.k8s.io
{{- end }}
