{{- if and .Values.interrogation.enabled (include "odigos.secretExists" .) .Values.interrogation.modelGateway.apiKey (not .Values.interrogation.modelGateway.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: odigos-interrogation-model
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: odigos-interrogation
    odigos.io/system-object: "true"
type: Opaque
data:
  api-key: {{ .Values.interrogation.modelGateway.apiKey | b64enc | quote }}
{{- end }}
